name: build_docs
on: [workflow_dispatch]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: blender/blender
          path: blender-git
          submodules: "true"

      - uses: actions/checkout@v3
        with:
          path: main

      - run: sudo apt-get tree
      - run: tree -L 2 --dirsfirst

      - run: python -V
      - run: which python

      - run: python -m ensurepip
      - run: python -m pip install mkdocs mkdocs-material lightgallery mkdocstrings mkdocs-autorefs

      - run: PYTHONPATH=$PYTHONPATH:blender-git/blender/release/
      - run: $PYTHONPATH
