name: build_docs
on: [workflow_dispatch]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: CAD_Sketcher
      - uses: actions/checkout@v3
        with:
          repository: blender/blender
          path: blender-git
          submodules: "true"

      - run: sudo apt-get install tree
      - run: tree -L 2 --dirsfirst

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
      - run: pip install markdown mkdocs mkdocs-material mkdocstrings mkdocs-autorefs lightgallery mkdocstrings-python

      - run: PYTHONPATH=$PYTHONPATH:blender-git/blender/release/scripts/modules:.
      - run: echo $PYTHONPATH

      - run: python3.10 -m mkdocs build -f ./CAD_Sketcher/mkdocs.yml
