name: build_docs
on: [workflow_dispatch]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: blender/blender
          path: blender-git
          submodules: "true"

      - run: sudo apt-get install tree
      - run: tree -L 2 --dirsfirst

      - uses: actions/setup-python@v4
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            markdown<3
            mkdocs
            mkdocs-material
            lightgallery
            mkdocstrings
            mkdocs-autorefs

      - run: python -V
      - run: which python

      - run: PYTHONPATH=$PYTHONPATH:blender-git/blender/release/scripts/modules
      - run: echo $PYTHONPATH

      - uses: mhausenblas/mkdocs-deploy-gh-pages@master
